# Generated by Django 4.2.23 on 2025-07-24 13:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=512)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('target_type', models.CharField(choices=[('domain', 'Domain'), ('ip', 'Ip'), ('asn', 'Asn'), ('url', 'Url'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('fail', 'Fail')], default='pending', max_length=16)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cmd', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ok', 'Ok'), ('fail', 'Fail'), ('timeout', 'Timeout')], default='pending', max_length=16)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('stdout_path', models.TextField(blank=True)),
                ('stderr_path', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agent.job')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
