# Generated by Django 4.2.23 on 2025-07-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='step',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
